name: Use Custom Greeting Action

on: [ workflow_dispatch ]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Greet with custom action
        uses: euforic/tester@main
        with:
          user-name: "Alice"
