name: Use Custom Greeting Action

on:
  workflow_dispatch:
    inputs:
      user-name:
        description: 'Name of the user to greet'
        required: true
        default: 'World' # This is optional. Without it, the GUI will prompt for a value.

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Greet with custom action
        uses: euforic/tester@main
